#!/usr/bin/env python3

import asyncio
import signal
import urwid
from playerlib.player import *

def create_screen():
    screen = urwid.raw_display.Screen()
    try:
        screen.set_terminal_properties(256)
    except:
        pass
    return screen

def main():
    signal.signal(signal.SIGINT, signal.SIG_IGN)
    Player(asyncio.get_event_loop(), create_screen()).run()

if __name__ == '__main__':
    main()

