#!/usr/bin/env python3

import asyncio
import logging
import signal
import urwid
from playerlib.player import *
from playerlib.config import *

def create_screen():
    screen = urwid.raw_display.Screen()
    try:
        screen.set_terminal_properties(256)
    except Exception as e:
        logging.warning('Cannot setup 256 colors: {}'.format(str(e)))
    return screen

def hack_urwid_asyncio():
    # For lower idle CPU usage
    urwid.AsyncioEventLoop._idle_emulation_delay = 1.0/60

def main():
    logging.basicConfig(level=logging.DEBUG,
        format='%(asctime)s %(name)-20s %(levelname)-10s %(message)s',
        datefmt='%m-%d %H:%M:%S',
        filename='log.log',
        filemode='w')
    logging.info('Starting')
    config = Config()
    signal.signal(signal.SIGINT, signal.SIG_IGN)
    hack_urwid_asyncio()
    Player(urwid.AsyncioEventLoop(loop=asyncio.get_event_loop()), create_screen(), config).run()
    logging.info('Exitting')

if __name__ == '__main__':
    main()

