#!/usr/bin/env python3

import logging
from playerlib.player import *

def main():
    logging.basicConfig(level=logging.DEBUG,
        format='%(asctime)s %(name)-20s %(levelname)-10s %(message)s',
        datefmt='%m-%d %H:%M:%S',
        filename='player.log',
        filemode='w')
    Player().run()

if __name__ == '__main__':
    main()

