#!/usr/bin/env python3

import logging
import sys
import unittest
from test.backend_factory_tests import *
from test.backend_interface_tests import *
from test.command_handler_tests import *
from test.command_panel_completer_tests import *
from test.command_panel_tests import *
from test.cueparser_tests import *
from test.file_browser_tests import *
from test.helpers_tests import *
from test.mplayer_backend_tests import *
from test.playback_controller_tests import *
from test.playlist_tests import *
from test.track_tests import *
from test.tracks_factory_tests import *
from test.user_input_tests import *

if __name__ == '__main__':
    logging.basicConfig(stream=sys.stderr)
    unittest.main()

